-- =========================================================
-- DEPRECATED — DO NOT IMPORT THIS FILE
--
-- The schema is now managed by versioned migrations, so that an existing
-- database can be upgraded without being dropped and re-imported
-- (PROJECT_RULES.md Rule 8, §6.10).
--
-- This file is intentionally left empty of DDL because the schema it used to
-- contain is now OUT OF DATE: it lacks product soft-delete, the order
-- snapshot columns, the corrected foreign keys, the indexes, the stock CHECK
-- constraint and the contact_messages table. Importing it would silently
-- reintroduce the ON DELETE CASCADE defect that destroyed order history when
-- a product was deleted.
--
-- SET UP OR UPGRADE THE DATABASE WITH:
--
--     php database/migrate.php
--
-- Other useful commands:
--
--     php database/migrate.php --status    show applied/pending migrations
--     php database/migrate.php --backup    dump the database before migrating
--
-- The migrations themselves live in database/migrations/ and are applied in
-- filename order, each exactly once, tracked in the `migrations` table.
-- =========================================================

SELECT 'This file is deprecated. Run: php database/migrate.php' AS `READ ME`;
